spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:23306/tacocloud
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

