version: '3.9'

services:
  mysql:
    image: mysql:8.0.32
    container_name: tc-mysql
    restart: always
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    shm_size: 256m
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: tacocloud
      MYSQL_PASSWORD: 123456
      LANG=: en_US.UTF-8
    networks:
      - tc-network
    ports:
      - "23306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA}:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
  redis:
    image: redis:7.0
    container_name: tc-redis
    hostname: redis
    restart: always
    ports:
      - "26379:6379"
    volumes:
      - ${REDIS_DATA}:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]
    networks:
      - tc-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis-commander:
    image: spryker/redis-commander:0.8.0
    container_name: tc-redis-commander
    hostname: redis-commander
    restart: always
    ports:
      - "18081:8081"
    environment:
      - TZ=Asia/Shanghai
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456
    networks:
      - tc-network
    depends_on:
      redis:
        condition: service_healthy


networks:
  tc-network:
    name: tc-network
    driver: bridge